os: linux
dist: xenial
language: cpp
compiler: gcc
script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
    - cmake --build . --target package
deploy:
    provider: script
    skip_cleanup: true
    script:
        - curl -T travis-test-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ukokoslik:$BINTRAY_API_KEY "https://api.bintray.com/content/kokoslik/travis-test/test/$TRAVIS_BUILD_NUMBER/travis-test-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64"